### ISSUE TITLE
地標命名問題

### ISSUE THREAD

**Issue by myong3** [willychang21/MapboxARGame#1]
https://github.com/mapbox/mapbox-unity-sdk/issues/784

**Comment by willychang21** [comment]
You can use the same scripts in AR as well as non-AR use cases. You can use the scripts used in InteractiveVectorMap in your application in AR. You might have to tweak the interaction logic based on your applications use case.

For the object names, they are named using the type+FeatureID convention. Currently we don't have plans to change this naming convention since it will be very difficult to cover all possible ways of naming. You can change this by modifying the code for your own use.
mapbox-unity-sdk/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/ModifierStack.cs

Line 186 in d2a85ea

 _tempVectorEntity.GameObject.name = type + " - " + feature.Data.Id;

**Comment by willychang21** [comment]
PrefabModifier.cs
        `go.name = ve.Feature.Data.Id.ToString();`
改成`go.name = ve.Feature.Properties["title"].ToString();`
